server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://192.168.0.0:3306/xxx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: maria566bc
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      validation-query: SELECT 1
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      keep-alive: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

  redis:
    database: 0
    host: 192.168.0.0
    port: 6379
    password: xxx
    timeout: 3000
    jedis:
      pool:
        max-active: 100
        max-wait: 1500
        max-idle: 10
        min-idle: 0
---
mybatis-plus:
  mapper-locations: classpath:mappers/**.xml
  global-config:
    sql-parser-cache: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
---
eth:
  enabled: true
  confirm_block_no: 3
  main:
    address: "xxx"
  collect:
    address: "xxx"
  gas:
    limit: 100000
  point:
    #url: https://mainnet-eth.token.im
    url: http://127.0.0.1:8545/
  #    url: http://47.56.201.255:8545/


